CREATE SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_PRODUCT;
CREATE SEQUENCE SEQ_ORDER;

CREATE TABLE TBL_MEMBER(
   MEMBER_NUMBER NUMBER PRIMARY KEY,
   MEMBER_ID VARCHAR2(1000),
   MEMBER_NAME VARCHAR2(1000),
   MEMBER_BIRTH DATE
);

CREATE TABLE TBL_PRODUCT(
   PRODUCT_NUMBER NUMBER PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(1000),
   PRODUCT_PRICE NUMBER,
   PRODUCT_STOCK NUMBER
);

CREATE TABLE TBL_ORDER(
   ORDER_NUMBER NUMBER PRIMARY KEY,
   PRODUCT_NUMBER NUMBER,
   ORDER_COUNT NUMBER,
   ORDER_PRICE NUMBER,
   MEMBER_NUMBER NUMBER,
   CONSTRAINT TBL_ORDER_FK_PRODUCT_NUMBER FOREIGN KEY (PRODUCT_NUMBER)
   REFERENCES TBL_PRODUCT(PRODUCT_NUMBER),
   CONSTRAINT TBL_ORDER_FK_MEMBER_NUMBER FOREIGN KEY (MEMBER_NUMBER)
   REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_PRODUCT;
SELECT * FROM TBL_ORDER;




